name: Build Documentation
description: 'Build Documentation.'

runs:
  using: composite
  steps:
    - name: Build Documentation
      shell: bash
      run: |
        dotnet tool update -g docfx
        docfx metadata
        docfx build
