#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LaunchDarkly.Xamarin.Android.Tests.Resource", IsApplication=true)]

namespace LaunchDarkly.Xamarin.Android.Tests
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::LaunchDarkly.Xamarin.Android.Tests.Resource.Layout.test_suite;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int alpha = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int coordinatorLayoutStyle = 2130771968;
			
			// aapt resource value: 0x7f010011
			public const int font = 2130771985;
			
			// aapt resource value: 0x7f01000a
			public const int fontProviderAuthority = 2130771978;
			
			// aapt resource value: 0x7f01000d
			public const int fontProviderCerts = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int fontProviderFetchStrategy = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int fontProviderFetchTimeout = 2130771983;
			
			// aapt resource value: 0x7f01000b
			public const int fontProviderPackage = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int fontProviderQuery = 2130771980;
			
			// aapt resource value: 0x7f010010
			public const int fontStyle = 2130771984;
			
			// aapt resource value: 0x7f010013
			public const int fontVariationSettings = 2130771987;
			
			// aapt resource value: 0x7f010012
			public const int fontWeight = 2130771986;
			
			// aapt resource value: 0x7f010001
			public const int keylines = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int layout_anchor = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int layout_anchorGravity = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int layout_behavior = 2130771971;
			
			// aapt resource value: 0x7f010008
			public const int layout_dodgeInsetEdges = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int layout_insetEdge = 2130771975;
			
			// aapt resource value: 0x7f010005
			public const int layout_keyline = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int statusBarBackground = 2130771970;
			
			// aapt resource value: 0x7f010014
			public const int ttcIndex = 2130771988;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060003
			public const int notification_action_color_filter = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int notification_icon_bg_color = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int notification_material_background_media_default_color = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int primary_text_default_material_dark = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int ripple_material_light = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int secondary_text_default_material_dark = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int secondary_text_default_material_light = 2131099654;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070008
			public const int compat_button_inset_horizontal_material = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int compat_button_inset_vertical_material = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int compat_button_padding_horizontal_material = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int compat_button_padding_vertical_material = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int compat_control_corner_material = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int compat_notification_large_icon_max_height = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int compat_notification_large_icon_max_width = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int notification_action_icon_size = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int notification_action_text_size = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int notification_big_circle_margin = 2131165201;
			
			// aapt resource value: 0x7f070005
			public const int notification_content_margin_start = 2131165189;
			
			// aapt resource value: 0x7f070012
			public const int notification_large_icon_height = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int notification_large_icon_width = 2131165203;
			
			// aapt resource value: 0x7f070006
			public const int notification_main_column_padding_top = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int notification_media_narrow_margin = 2131165191;
			
			// aapt resource value: 0x7f070014
			public const int notification_right_icon_size = 2131165204;
			
			// aapt resource value: 0x7f070004
			public const int notification_right_side_padding_top = 2131165188;
			
			// aapt resource value: 0x7f070015
			public const int notification_small_icon_background_padding = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int notification_small_icon_size_as_large = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int notification_subtext_size = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int notification_top_pad = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int notification_top_pad_large_text = 2131165209;
			
			// aapt resource value: 0x7f070000
			public const int subtitle_corner_radius = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int subtitle_outline_width = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int subtitle_shadow_offset = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int subtitle_shadow_radius = 2131165187;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int notification_action_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg_low = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_icon_background = 2130837511;
			
			// aapt resource value: 0x7f02000a
			public const int notification_template_icon_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_low_bg = 2130837515;
			
			// aapt resource value: 0x7f020008
			public const int notification_tile_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notify_panel_notification_icon_bg = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0032
			public const int OptionHostName = 2131361842;
			
			// aapt resource value: 0x7f0a0033
			public const int OptionPort = 2131361843;
			
			// aapt resource value: 0x7f0a0031
			public const int OptionRemoteServer = 2131361841;
			
			// aapt resource value: 0x7f0a0041
			public const int OptionsButton = 2131361857;
			
			// aapt resource value: 0x7f0a003c
			public const int ResultFullName = 2131361852;
			
			// aapt resource value: 0x7f0a003e
			public const int ResultMessage = 2131361854;
			
			// aapt resource value: 0x7f0a003d
			public const int ResultResultState = 2131361853;
			
			// aapt resource value: 0x7f0a003b
			public const int ResultRunSingleMethodTest = 2131361851;
			
			// aapt resource value: 0x7f0a003f
			public const int ResultStackTrace = 2131361855;
			
			// aapt resource value: 0x7f0a0037
			public const int ResultsFailed = 2131361847;
			
			// aapt resource value: 0x7f0a0034
			public const int ResultsId = 2131361844;
			
			// aapt resource value: 0x7f0a0038
			public const int ResultsIgnored = 2131361848;
			
			// aapt resource value: 0x7f0a0039
			public const int ResultsInconclusive = 2131361849;
			
			// aapt resource value: 0x7f0a003a
			public const int ResultsMessage = 2131361850;
			
			// aapt resource value: 0x7f0a0036
			public const int ResultsPassed = 2131361846;
			
			// aapt resource value: 0x7f0a0035
			public const int ResultsResult = 2131361845;
			
			// aapt resource value: 0x7f0a0040
			public const int RunTestsButton = 2131361856;
			
			// aapt resource value: 0x7f0a0042
			public const int TestSuiteListView = 2131361858;
			
			// aapt resource value: 0x7f0a0020
			public const int action0 = 2131361824;
			
			// aapt resource value: 0x7f0a001d
			public const int action_container = 2131361821;
			
			// aapt resource value: 0x7f0a0024
			public const int action_divider = 2131361828;
			
			// aapt resource value: 0x7f0a001e
			public const int action_image = 2131361822;
			
			// aapt resource value: 0x7f0a001f
			public const int action_text = 2131361823;
			
			// aapt resource value: 0x7f0a002e
			public const int actions = 2131361838;
			
			// aapt resource value: 0x7f0a0017
			public const int all = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int async = 2131361816;
			
			// aapt resource value: 0x7f0a0019
			public const int blocking = 2131361817;
			
			// aapt resource value: 0x7f0a0008
			public const int bottom = 2131361800;
			
			// aapt resource value: 0x7f0a0021
			public const int cancel_action = 2131361825;
			
			// aapt resource value: 0x7f0a0009
			public const int center = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int center_horizontal = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int center_vertical = 2131361803;
			
			// aapt resource value: 0x7f0a0029
			public const int chronometer = 2131361833;
			
			// aapt resource value: 0x7f0a000c
			public const int clip_horizontal = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int clip_vertical = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int end = 2131361806;
			
			// aapt resource value: 0x7f0a0030
			public const int end_padder = 2131361840;
			
			// aapt resource value: 0x7f0a000f
			public const int fill = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int fill_horizontal = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int fill_vertical = 2131361809;
			
			// aapt resource value: 0x7f0a001a
			public const int forever = 2131361818;
			
			// aapt resource value: 0x7f0a002b
			public const int icon = 2131361835;
			
			// aapt resource value: 0x7f0a002f
			public const int icon_group = 2131361839;
			
			// aapt resource value: 0x7f0a002a
			public const int info = 2131361834;
			
			// aapt resource value: 0x7f0a001b
			public const int italic = 2131361819;
			
			// aapt resource value: 0x7f0a0012
			public const int left = 2131361810;
			
			// aapt resource value: 0x7f0a0000
			public const int line1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int line3 = 2131361793;
			
			// aapt resource value: 0x7f0a0023
			public const int media_actions = 2131361827;
			
			// aapt resource value: 0x7f0a0016
			public const int none = 2131361814;
			
			// aapt resource value: 0x7f0a001c
			public const int normal = 2131361820;
			
			// aapt resource value: 0x7f0a002d
			public const int notification_background = 2131361837;
			
			// aapt resource value: 0x7f0a0026
			public const int notification_main_column = 2131361830;
			
			// aapt resource value: 0x7f0a0025
			public const int notification_main_column_container = 2131361829;
			
			// aapt resource value: 0x7f0a0013
			public const int right = 2131361811;
			
			// aapt resource value: 0x7f0a002c
			public const int right_icon = 2131361836;
			
			// aapt resource value: 0x7f0a0027
			public const int right_side = 2131361831;
			
			// aapt resource value: 0x7f0a0014
			public const int start = 2131361812;
			
			// aapt resource value: 0x7f0a0022
			public const int status_bar_latest_event_content = 2131361826;
			
			// aapt resource value: 0x7f0a0002
			public const int tag_transition_group = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int tag_unhandled_key_event_manager = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int tag_unhandled_key_listeners = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int text = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int text2 = 2131361798;
			
			// aapt resource value: 0x7f0a0028
			public const int time = 2131361832;
			
			// aapt resource value: 0x7f0a0007
			public const int title = 2131361799;
			
			// aapt resource value: 0x7f0a0015
			public const int top = 2131361813;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int cancel_button_image_alpha = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int status_bar_notification_info_maxnum = 2131230721;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int notification_action = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int notification_action_tombstone = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int notification_media_action = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int notification_media_cancel_action = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int notification_template_big_media = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_template_big_media_custom = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int notification_template_big_media_narrow = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int notification_template_big_media_narrow_custom = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int notification_template_custom_big = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int notification_template_icon_group = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int notification_template_lines_media = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int notification_template_media = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int notification_template_media_custom = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int notification_template_part_chronometer = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int notification_template_part_time = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int options = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int results = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int test_result = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int test_suite = 2130968594;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090000
			public const int status_bar_notification_info_overflow = 2131296256;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050006
			public const int TextAppearance_Compat_Notification = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int TextAppearance_Compat_Notification_Info = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int TextAppearance_Compat_Notification_Line2 = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int TextAppearance_Compat_Notification_Media = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int TextAppearance_Compat_Notification_Time = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int TextAppearance_Compat_Notification_Title = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int Widget_Compat_NotificationActionContainer = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int Widget_Compat_NotificationActionText = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int Widget_Support_CoordinatorLayout = 2131034117;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771977};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			public static int[] CoordinatorLayout = new int[] {
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_keylines = 0;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_statusBarBackground = 1;
			
			public static int[] CoordinatorLayout_Layout = new int[] {
					16842931,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 2
			public const int CoordinatorLayout_Layout_layout_anchor = 2;
			
			// aapt resource value: 4
			public const int CoordinatorLayout_Layout_layout_anchorGravity = 4;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_Layout_layout_behavior = 1;
			
			// aapt resource value: 6
			public const int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 6;
			
			// aapt resource value: 5
			public const int CoordinatorLayout_Layout_layout_insetEdge = 5;
			
			// aapt resource value: 3
			public const int CoordinatorLayout_Layout_layout_keyline = 3;
			
			public static int[] FontFamily = new int[] {
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 6
			public const int FontFamilyFont_font = 6;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontStyle = 5;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontVariationSettings = 8;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontWeight = 7;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
