version: 2

repo:
  public: dotnet-client-sdk
  private: dotnet-client-sdk-private

branches:
  - name: main
    description: 3.x
  - name: 2.x
  - name: 1.x

jobs:
  # The main build happens on a Mac host
  - circleCI:
      mac:
        xcode: "13.4.1"
      context: org-global
      steps:
        - step: prepare
        - step: build
        - step: test
        - step: publish

  # Documentation is built in a Linux container
  - template:
      name: dotnet6-linux
      skip:
        - test
        - publish
        - publish-dry-run
    env:
      BUILDFRAMEWORKS: netstandard2.0
      LD_RELEASE_DOCS_TARGET_FRAMEWORK: netstandard2.0
      LD_RELEASE_DOCS_ASSEMBLIES: LaunchDarkly.ClientSdk LaunchDarkly.CommonSdk

publications:
  - url: https://www.nuget.org/packages/LaunchDarkly.ClientSdk
    description: NuGet

documentation:
  title: LaunchDarkly Client-Side SDK for .NET
  gitHubPages: true

sdk:
  displayName: ".NET (client-side)"
