on:
  workflow_dispatch:

name: Publish Docs
jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed if using OIDC to get release secrets.
      contents: write # Needed in this case to write github pages.
    steps:
      - uses: actions/checkout@v4
      - id: build
        name: Build and Test
        uses: ./.github/actions/ci

      - id: publish
        name: Publish Documentation
        uses: ./.github/actions/publish-docs
        with:
          token: ${{secrets.GITHUB_TOKEN}}
