on:
  workflow_dispatch:

name: Publish Docs
jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed if using OIDC to get release secrets.
      contents: write # Needed in this case to write github pages.
    steps:
      - uses: actions/checkout@v4
        
      - uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.0.1
        name: Get secrets
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}

      - id: build
        name: Build and Test
        uses: ./.github/actions/ci

      - id: publish
        name: Publish Documentation
        uses: ./.github/actions/publish-docs
        with:
          token: ${{secrets.GITHUB_TOKEN}}
