name: Release Please
on:
  push:
    branches:
      - main
      - ta/sc-233251/release-please-support
      - ta/sc-233251/release-please-support-fake-main

jobs:
  release-please:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed if using OIDC to get release secrets.
      contents: write # Contents and pull-requests are for release-please to make releases.
      pull-requests: write

    steps:
      # Normally a workflow cannot trigger another workflow. For this workflow we need to create a
      # tag that will trigger another workflow. Github determines that something is created by
      # a workflow/bot based on the token. So to allow the tag creation to trigger a workflow
      # we must use a personal access token.
      - uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.0.1
        name: "Get PAT"
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
          ssm_parameter_pairs: "/production/common/releasing/flutter_gh_pat = GITHUB_PAT"

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ env.GITHUB_PAT }}
          target-branch: ${{ github.ref_name }}
